openapi: 3.0.1
info:
  title: People app
  version: "1.0"
  description: People simple app

paths:
  /people/api/person/{personId}:
    get:
      operationId: getPerson
      parameters:
        - name: personId
          in: path
          schema:
            type: string
            x-scala-type: org.robmaksoftware.domain.PersonId
          required: true
      responses:
        '200':
          description: person by id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PersonDto'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Person not found.
    delete:
      operationId: deletePerson
      parameters:
        - name: personId
          in: path
          schema:
            type: string
            x-scala-type: org.robmaksoftware.domain.PersonId
          required: true
      responses:
        '200':
          description: person deleted
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          description: Person not found.

  /people/api/all:
    get:
      operationId: getAllPeople
      parameters:
        - name: offset
          in: query
          schema:
            type: integer
            x-scala-type: Int
          required: false
        - name: limit
          in: query
          schema:
            type: integer
            x-scala-type: Int
          required: false
      responses:
        '200':
          description: all people
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PeopleDto'
        '400':
          $ref: '#/components/responses/BadRequest'

components:

  schemas:

    PeopleDto:
      type: object
      required:
        - people
      properties:
        people:
          type: array
          x-scala-array-type: List
          items:
            $ref: '#/components/schemas/PersonDto'

    PersonDto:
      type: object
      required:
        - id
        - name
        - age
        - sex
        - credit
        - joined
      properties:
        id:
          type: string
        name:
          type: string
        age:
          type: integer
          x-scala-type: Int
        sex:
          type: string
        credit:
          type: number
          x-scala-type: Double
        joined:
          type: number
          x-scala-type: Long

  responses:
    BadRequest:
      description: Bad Request
      content:
        application/json:
          schema:
            type: string